services:
  unifi-dns-manager:
    build: .
    container_name: unifi-dns-manager
    ports:
      - "52638:52638"
    volumes:
      - data:/app/data
    restart: unless-stopped
    environment:
      - TZ=UTC
    labels:
      - "com.docker.compose.project=unifi-dns-manager"
      - "com.docker.compose.service=app"
      - "maintainer=openhands@all-hands.dev"

volumes:
  data:
